name: linting

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: 'Source'
          extensions: 'h,cpp'
          clangFormatVersion: 10
