name: pull_request

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: 'Source'
          extensions: 'h,cpp'
          clangFormatVersion: 10

  build_x86_64:
    needs: [linting]
    runs-on: ubuntu-20.04
    container: stonepreston/juce_compiler:latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j8
